// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UBahnApi.Data;

#nullable disable

namespace UBahnApi.Migrations
{
    [DbContext(typeof(UBahnContext))]
    [Migration("20260613071902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UBahnApi.Models.Fahrzeit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DauerMinuten")
                        .HasColumnType("int");

                    b.Property<int>("NachStationId")
                        .HasColumnType("int");

                    b.Property<int>("VonStationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NachStationId");

                    b.HasIndex("VonStationId");

                    b.ToTable("Fahrzeiten");
                });

            modelBuilder.Entity("UBahnApi.Models.Linie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Linien");
                });

            modelBuilder.Entity("UBahnApi.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LinieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinieId");

                    b.ToTable("Stationen");
                });

            modelBuilder.Entity("UBahnApi.Models.Fahrzeit", b =>
                {
                    b.HasOne("UBahnApi.Models.Station", "NachStation")
                        .WithMany()
                        .HasForeignKey("NachStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UBahnApi.Models.Station", "VonStation")
                        .WithMany()
                        .HasForeignKey("VonStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NachStation");

                    b.Navigation("VonStation");
                });

            modelBuilder.Entity("UBahnApi.Models.Station", b =>
                {
                    b.HasOne("UBahnApi.Models.Linie", "Linie")
                        .WithMany("Stationen")
                        .HasForeignKey("LinieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Linie");
                });

            modelBuilder.Entity("UBahnApi.Models.Linie", b =>
                {
                    b.Navigation("Stationen");
                });
#pragma warning restore 612, 618
        }
    }
}
